package dsw.gerumap.app.core.messagegen;

public enum EventType {

    TRY_TO_DELETE_PROJECTEXPLORER, NODE_CANNOT_HAVE_CHILDREN , MUST_HAVE_NAME, NODE_NOT_SELECTED, NO_ELEMENT_FOUND, YOU_DONT_HAVE_INITIAL_POINT, YOU_HAVE_TO_SELECT_PROJECT,YOU_HAVE_TO_SELECT_MINDMAP;
}
